'''https://www.geeksforgeeks.org/print-subsequences-string/

Given a string, we have to find out all subsequences of it. A String is a subsequence of a given String, that is generated by deleting some character of a given string without changing its order.

Examples: 
Input : abc
Output : a, b, c, ab, bc, ac, abc

Input : aaa
Output : a, aa, aaa 

'''
# Below is the implementation of the above approach


def printSubsequence(input, output):

    # Base Case
    # if the input is empty print the output string
    if len(input) == 0:
        print(output, end=' ')
        return

    # output is passed with including the
    # 1st character of input string
    printSubsequence(input[1:], output+input[0])

    # output is passed without including the
    # 1st character of input string
    printSubsequence(input[1:], output)


# Driver code
# output is set to null before passing in
# as a parameter
output = ""
input = "abcd"

printSubsequence(input, output)
