#!/usr/bin/env python3
"""Give every note folder an entry note (Map of Content) that links its contents.

For each folder holding live notes (archived drafts and private paths excluded):
- no entry note yet: create README.md with frontmatter, a title, and a
  generated index of its sub-sections and notes (a folder holding a single
  note and no sub-folders uses that note as its entry instead);
- a hand-written entry note: add a generated "Also in this folder" section that
  lists only the notes and sub-sections the note does not already link.

Generated text sits between the markers below, so re-running replaces it and
never touches hand-written text. Links are relative Markdown links, which work
in both Obsidian and GitHub.

Usage:
    python3 tools/build_mocs.py            # dry run
    python3 tools/build_mocs.py --apply
"""

from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from pathlib import Path, PurePosixPath
from urllib.parse import quote

import audit_vault as av
from vault_schema import SCOPES, tracks_for

START = "<!-- moc:start (generated by tools/build_mocs.py; edits inside are overwritten) -->"
END = "<!-- moc:end -->"
BLOCK_RE = re.compile(re.escape(START) + r".*?" + re.escape(END) + r"\n?", re.S)


def pretty(name: str) -> str:
    name = re.sub(r"^\d+\s*-\s*|^\d+[-_ ]", "", name)
    return re.sub(r"[-_]+", " ", name).strip() or name


def note_title(path: Path) -> str:
    for line in path.read_text(errors="ignore").splitlines()[:40]:
        if line.startswith("# "):
            return line[2:].strip()
    return pretty(path.stem)


def link(frm: str, to: str, text: str) -> str:
    rel = str(PurePosixPath(to).relative_to(frm)) if to.startswith(frm + "/") else to
    return f"[{text.replace('[', '(').replace(']', ')')}]({quote(rel, safe='/.-_~')})"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--repo", type=Path, default=Path(__file__).resolve().parent.parent)
    ap.add_argument("--apply", action="store_true")
    args = ap.parse_args()
    repo = args.repo.resolve()

    tracked = av.tracked_files(repo)
    resolver = av.Resolver(tracked)
    files = [f for f in tracked if not av.is_private(f)]
    live = [f for f in files if f.endswith(".md") and not av.ARCHIVED_RE.search(f)]
    names: dict[str, set[str]] = defaultdict(set)
    for f in files:
        names[str(PurePosixPath(f).parent)].add(PurePosixPath(f).name.lower())

    # Folders that hold live notes, plus all their ancestors (so every level gets an index).
    folders: set[str] = set()
    for f in live:
        p = PurePosixPath(f).parent
        while str(p) not in (".", "") and not p.name.startswith("."):
            folders.add(str(p))
            p = p.parent
    folders = {d for d in folders if not av.ARCHIVED_RE.search(d + "/") and not any(part.startswith(".") for part in PurePosixPath(d).parts)}

    direct = defaultdict(list)
    for f in live:
        direct[str(PurePosixPath(f).parent)].append(f)
    has_sub = {str(PurePosixPath(d).parent) for d in folders}

    def entry_path(d: str) -> str:
        e = av.entry_note(d, names[d])
        if e is None:
            if len(direct[d]) == 1 and d not in has_sub:  # a lone note is its folder's entry
                return direct[d][0]
            return f"{d}/README.md"
        return next(f for f in files if str(PurePosixPath(f).parent) == d and PurePosixPath(f).name.lower() == e)

    entries = {d: entry_path(d) for d in folders}
    created = updated = 0
    for d in sorted(folders):
        entry = entries[d]
        path = repo / entry
        existing = path.read_text(errors="ignore") if path.exists() else None
        body = BLOCK_RE.sub("", existing) if existing else ""

        subs = sorted(c for c in folders if str(PurePosixPath(c).parent) == d)
        notes = sorted(f for f in live if str(PurePosixPath(f).parent) == d and f != entry)

        if existing is not None:  # only list what the hand-written note does not already reach
            linked = set()
            for l in av.extract_links(entry, body):
                res = resolver.wiki(entry, l.target) if l.kind == "wiki" else resolver.md(entry, l.target)
                if isinstance(res, str):
                    linked.add(res)
            subs = [c for c in subs if entries[c] not in linked and c not in linked]
            notes = [n for n in notes if n not in linked]
            if not subs and not notes:
                if existing != body and args.apply:
                    path.write_text(body)
                continue

        lines = [START]
        heading = "## Also in this folder" if existing is not None else "## Contents"
        lines += [heading, ""]
        if subs:
            lines += ["**Sections**", ""] + [f"- {link(d, entries[c], pretty(PurePosixPath(c).name))}" for c in subs] + [""]
        if notes:
            lines += ["**Notes**", ""] + [f"- {link(d, n, note_title(repo / n))}" for n in notes] + [""]
        lines.append(END)
        block = "\n".join(lines) + "\n"

        if existing is None:
            track = ", ".join(tracks_for(d))
            head = [
                "---", "type: moc", f"track: [{track}]", "level:", "status: draft", "last_reviewed:", "sources: []", "---", "",
                f"# {pretty(PurePosixPath(d).name)}", "",
            ]
            scope = SCOPES.get(d)
            if scope:
                head += [scope, ""]
            text = "\n".join(head) + block
            created += 1
        else:
            text = body.rstrip("\n") + "\n\n" + block
            updated += 1
        if args.apply:
            path.write_text(text)

    print(f"folders: {len(folders)}")
    print(f"entry_notes_created: {created}")
    print(f"entry_notes_extended: {updated}")
    if not args.apply:
        print("dry run; pass --apply to write")
    return 0


if __name__ == "__main__":
    sys.exit(main())
