#!/usr/bin/env python3
"""Regenerate a "Zero to Godhood" book's SUMMARY.md from the files on disk.

Layout it expects: Front_Matter/, Volume_NN_*/Chapter_*/<chapter>.md, and
Appendices/. Archived or consolidated copies (_archive/, _consolidated*/) are
skipped, and byte-identical duplicates are listed once. Titles come from each
file's first "# " heading, falling back to a cleaned file name.

Usage:
    python3 tools/gen_book_summary.py "02-Programming-Languages/C++/CPP_Zero_to_Godhood"
"""

from __future__ import annotations

import argparse
import hashlib
import re
import sys
from pathlib import Path
from urllib.parse import quote

SKIP_RE = re.compile(r"(^|/)(_archive|_consolidated[^/]*)(/|$)")
NUM_RE = re.compile(r"(\d+)")


def number(name: str) -> tuple[int, str]:
    m = NUM_RE.search(name)
    return (int(m.group(1)) if m else 10**6, name.lower())


def title(path: Path) -> str:
    for line in path.read_text(errors="ignore").splitlines():
        if line.startswith("# "):
            return line[2:].strip().strip("#").strip()
    return re.sub(r"_+", " ", path.stem).strip()


def notes(folder: Path, book: Path) -> list[Path]:
    out, seen = [], set()
    for p in sorted(folder.rglob("*.md"), key=lambda p: [number(part) for part in p.relative_to(folder).parts]):
        rel = p.relative_to(book).as_posix()
        if SKIP_RE.search(rel):
            continue
        digest = hashlib.sha1(p.read_bytes()).hexdigest()
        if digest in seen:
            continue
        seen.add(digest)
        out.append(p)
    return out


def cpp_label(name: str) -> str:
    """Folder names cannot hold "++" or "/": Foundation_C98_03 -> Foundation (C++98/03)."""
    name = re.sub(r"_(?:C|CPP)(\d\d)(?:_(\d\d))?$", lambda m: f" (C++{m.group(1)}{'/' + m.group(2) if m.group(2) else ''})", name)
    return name.replace("_", " ")


def entry(p: Path, book: Path) -> str:
    return f"- [{title(p)}]({quote(p.relative_to(book).as_posix(), safe='/.-_~')})"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("book", type=Path)
    args = ap.parse_args()
    book = args.book.resolve()

    lines = ["# Summary", "", "Generated by `tools/gen_book_summary.py` from the chapter files; re-run it instead of editing by hand.", ""]
    if (book / "Front_Matter").is_dir():
        lines += [entry(p, book) for p in notes(book / "Front_Matter", book)] + [""]
    for vol in sorted((d for d in book.glob("Volume_*") if d.is_dir()), key=lambda d: number(d.name)):
        m = re.match(r"Volume_(\d+)_(.*)", vol.name)
        heading = f"Volume {m.group(1)}: {cpp_label(m.group(2))}" if m else vol.name
        lines += [f"## {heading}", "", *[entry(p, book) for p in notes(vol, book)], ""]
    if (book / "Appendices").is_dir():
        lines += ["## Appendices", "", *[entry(p, book) for p in notes(book / "Appendices", book)], ""]

    (book / "SUMMARY.md").write_text("\n".join(lines))
    print(f"wrote {book / 'SUMMARY.md'}: {sum(1 for l in lines if l.startswith('- ['))} entries")
    return 0


if __name__ == "__main__":
    sys.exit(main())
